# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write # Changed from 'read' to 'write'
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        repository: ${{ github.repository }}
        token: ${{ secrets.GITHUB_TOKEN }}
        path: gh-pages
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
    - name: Clean Cache and Node Modules
      run: |
        rm -rf node_modules
        npm cache clean --force
    - name: Install dependencies
      run: npm ci
    - name: Update dependencies
      run: npm update
    - name: Build
      run: npm run build
    - name: Move the build to gh-pages
      run: |
        mv dist/* gh-pages
        rm -r dist
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        branch: gh-pages
        folder: gh-pages
