name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Clean Cache and Node Modules
        run: |
          rm -rf node_modules
          npm cache clean --force

      - name: Install dependencies
        run: npm ci

      - name: Update dependencies
        run: npm update

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build # This job depends on the 'build' job
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to deploy to GitHub Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gh-pages

      - name: Download production-ready build files
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Move the artifacts to correct location
        run: |
          mv dist/* gh-pages
          rm -r dist

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
